//! The `ACK` for a 2xx — [proxy-behavior](https://github.com/codewandler/sipx-clstr/blob/main/docs/specs/proxy-behavior.md)
//! §7.2 K3, RFC 3261 §17.1.1.3.
//!
//! One method, three messages, and only this one is the proxy's to forward:
//!
//! - **K1**, the `ACK` for a non-2xx going downstream, is generated by the client transaction that
//!   received the final response. The kernel owns it; nothing here is involved.
//! - **K2**, the `ACK` for a non-2xx arriving from upstream, is part of the server transaction that
//!   sent that response and is absorbed there (§17.2.1). It never reaches this module, because the
//!   kernel's transaction layer never hands it up.
//! - **K3**, the `ACK` for a 2xx, is a **separately routed request**: a transaction of its own that
//!   nothing answers. It takes the same validation, the same preprocessing, the same target
//!   determination and the same F1–F9 edits as any other forwarded request — through the same code,
//!   which is the point. `V-03` was a private path that skipped all four.
//!
//! What makes this a function rather than a [`ResponseContext`](crate::context::ResponseContext) is
//! the absence of a server transaction to answer. A context exists to aggregate responses and
//! eventually produce one; an `ACK` has none, so every refusal a context could reach — §7's `480`,
//! §4's `483` — is unavailable here. Modelling it as a context whose `Respond` effects the driver
//! quietly discarded would put that protocol rule in the driver, where the harness cannot see it and
//! where the next driver would have to reinvent it.
//!
//! So the outcome is total and explicit: either a request and the hop it goes to, or a reason it
//! cannot go anywhere. **Never a silent drop** — the reason is the record that stands in for the
//! response SIP does not have.

use bytes::Bytes;
use sipx_sip::Request;

use crate::config::ProxyConfig;
use crate::forward::{ForwardError, ForwardPlan, forward};
use crate::route;
use crate::validate::{Refusal, validate};

/// What to do with an `ACK` for a 2xx (§7.2 K3).
#[derive(Debug)]
pub enum AckRoute {
    /// Forward this, with no transaction of its own and no response, ever.
    Forward {
        /// The copy as it goes on the wire: `Max-Forwards` decremented, our `Via` pushed, the
        /// `Route` set preprocessed, no `Record-Route` added (RFC 6141 — a mid-dialog
        /// `Record-Route` changes no established route set).
        request: Box<Request>,
        /// The URI whose address it must reach — F7, off the copy.
        next_hop: Bytes,
    },
    /// It cannot be forwarded, and there is no response to send instead. The reason, for the record.
    Unroutable(AckRefusal),
}

/// Why an `ACK` was not forwarded.
///
/// Every variant is a **drop with a reason**. An `ACK` has no response in SIP (RFC 3261 §17.1.1.3),
/// which [cluster-config](https://github.com/codewandler/sipx-clstr/blob/main/docs/specs/cluster-config.md)
/// §8 V11 already relies on for the admission bound, so there is no status to answer with and
/// inventing one would put a response on a transaction that has none. What is available is saying
/// so, which is what this type is for.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AckRefusal {
    /// §4 refused it. The refusal's status is what a *respondable* method would have been answered;
    /// here it is only the reason the `ACK` stopped.
    Refused(Refusal),
    /// F1–F9 could not build a forwardable copy — an unparseable target, or `Record-Route`
    /// configuration that does not parse.
    NotForwardable(ForwardError),
}

impl AckRefusal {
    /// Why, in one static phrase — for a log line, and structurally incapable of carrying anything
    /// the far end sent.
    #[must_use]
    pub fn describe(&self) -> &'static str {
        match self {
            Self::Refused(Refusal::Drop) => "the ACK is not well-formed enough to forward",
            Self::Refused(Refusal::UnsupportedScheme) => {
                "the Request-URI's scheme is not forwarded"
            }
            Self::Refused(Refusal::TooManyHops) => "Max-Forwards reached zero",
            Self::Refused(Refusal::LoopDetected) => "the ACK came back round a loop",
            Self::Refused(Refusal::MaxBreadthExceeded) => "Max-Breadth reached zero",
            Self::Refused(Refusal::BadExtension(_)) => {
                "Proxy-Require names an unsupported extension"
            }
            Self::NotForwardable(_) => "no forwardable copy could be built",
        }
    }
}

/// Route an `ACK` for a 2xx: §§4, 5, 5.1 and §7's edits, and the hop it goes to.
///
/// The target set is predetermined by §5.1 T1 whatever the `To` tag says, because §17.1.1.3 settles
/// it for this method: the `ACK` for a 2xx is addressed to the dialog's remote target, and a proxy
/// that resolved that Request-URI as an address of record would deliver the acknowledgement to
/// whatever the registrar happened to hold under it — or, finding nothing, drop the one message that
/// concludes the call.
pub fn route_ack(request: Request, config: &ProxyConfig) -> AckRoute {
    let validated = match validate(&request, config) {
        Ok(validated) => validated,
        Err(refusal) => return AckRoute::Unroutable(AckRefusal::Refused(refusal)),
    };

    let mut request = request;
    route::preprocess(&mut request, config);
    let target = route::predetermined_target(&request);

    let plan = ForwardPlan {
        original: &request,
        validated: &validated,
        target: &target,
        // One copy, never a fork: an `ACK` acknowledges one response from one branch.
        index: 0,
        parallel_branches: 1,
        // RFC 6141, and the same rule `is_dialog_forming` applies to a re-INVITE: a mid-dialog
        // `Record-Route` does not alter an established route set, so it is bytes for nothing.
        record_route: false,
        token: None,
    };
    match forward(&plan, config) {
        Ok((_, forwarded)) => {
            let next_hop = route::next_hop_of(&forwarded);
            AckRoute::Forward {
                request: Box::new(forwarded),
                next_hop,
            }
        }
        Err(error) => AckRoute::Unroutable(AckRefusal::NotForwardable(error)),
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::config::CookieKey;
    use sipx_sip::{HeaderName, Method, RequestBuilder, Uri};

    fn config() -> ProxyConfig {
        ProxyConfig::new(
            "edge-1.example",
            Bytes::from_static(b"<sip:edge-1.example:5060;lr>"),
            CookieKey::new(Bytes::from_static(b"key")),
        )
    }

    /// An `ACK` for a 2xx as a phone builds one (RFC 3261 §13.2.2.4): the Request-URI is the
    /// dialog's remote target and the `Route` set is what the `Record-Route` established.
    fn ack(remote_target: &str, routes: &[&str], max_forwards: &str) -> Request {
        let mut builder = RequestBuilder::new(
            Method::Ack,
            Uri::parse(Bytes::copy_from_slice(remote_target.as_bytes())).expect("a URI"),
        )
        .header(HeaderName::CallId, "ack-tests")
        .unwrap()
        .cseq(1, &Method::Ack)
        .unwrap()
        .header(HeaderName::From, "<sip:alice@a.example>;tag=af")
        .unwrap()
        .header(HeaderName::To, "<sip:bob@b.example>;tag=bt")
        .unwrap()
        .header(HeaderName::MaxForwards, max_forwards.to_owned())
        .unwrap()
        .header(
            HeaderName::Via,
            "SIP/2.0/UDP alice.example;branch=z9hG4bK-a",
        )
        .unwrap();
        for route in routes {
            builder = builder
                .header(HeaderName::Route, (*route).to_owned())
                .unwrap();
        }
        builder.build()
    }

    fn header(request: &Request, name: &HeaderName) -> Option<String> {
        request
            .headers
            .value(name)
            .map(|value| String::from_utf8_lossy(&value).trim().to_owned())
    }

    #[test]
    fn a_route_set_ack_goes_to_the_remote_target_with_our_route_popped() {
        let outcome = route_ack(
            ack(
                "sip:bob@10.0.0.1:5062",
                &["<sip:edge-1.example:5060;lr>"],
                "70",
            ),
            &config(),
        );
        let AckRoute::Forward { request, next_hop } = outcome else {
            panic!("an ACK with a reachable remote target is forwarded: {outcome:?}");
        };
        assert_eq!(
            String::from_utf8_lossy(&next_hop),
            "sip:bob@10.0.0.1:5062",
            "our own Route was popped, so the remote target is the next hop"
        );
        assert_eq!(header(&request, &HeaderName::Route), None);
        assert_eq!(
            header(&request, &HeaderName::MaxForwards).as_deref(),
            Some("69")
        );
        assert_eq!(header(&request, &HeaderName::RecordRoute), None);
        assert!(
            header(&request, &HeaderName::Via).is_some_and(|via| via.contains("edge-1.example")),
            "a forwarded request carries our Via (F8)"
        );
    }

    #[test]
    fn a_second_proxys_route_is_the_next_hop_and_the_target_is_untouched() {
        let outcome = route_ack(
            ack(
                "sip:bob@10.0.0.1:5062",
                &["<sip:edge-1.example:5060;lr>", "<sip:p2.example;lr>"],
                "70",
            ),
            &config(),
        );
        let AckRoute::Forward { request, next_hop } = outcome else {
            panic!("forwarded: {outcome:?}");
        };
        assert_eq!(String::from_utf8_lossy(&next_hop), "sip:p2.example;lr");
        assert_eq!(
            String::from_utf8_lossy(&request.uri.to_bytes()),
            "sip:bob@10.0.0.1:5062",
            "the Request-URI stays the dialog's remote target"
        );
    }

    #[test]
    fn an_unforwardable_ack_is_an_explicit_outcome_and_never_a_response() {
        let outcome = route_ack(ack("sip:bob@10.0.0.1:5062", &[], "0"), &config());
        let AckRoute::Unroutable(refusal) = outcome else {
            panic!("Max-Forwards: 0 cannot be forwarded: {outcome:?}");
        };
        assert_eq!(refusal, AckRefusal::Refused(Refusal::TooManyHops));
        assert_eq!(refusal.describe(), "Max-Forwards reached zero");
    }
}
