//! The `ACK` for a 2xx — [proxy-behavior](https://github.com/codewandler/sipx-clstr/blob/main/docs/specs/proxy-behavior.md)
//! §7.2 K3, RFC 3261 §17.1.1.3.
//!
//! One method, three messages, and only this one is the proxy's to forward:
//!
//! - **K1**, the `ACK` for a non-2xx going downstream, is generated by the client transaction that
//!   received the final response. The kernel owns it; nothing here is involved.
//! - **K2**, the `ACK` for a non-2xx arriving from upstream, is part of the server transaction that
//!   sent that response and is absorbed there (§17.2.1). It never reaches this module, because the
//!   kernel's transaction layer never hands it up.
//! - **K3**, the `ACK` for a 2xx, is a **separately routed request**: a transaction of its own that
//!   nothing answers. It takes the same validation, the same preprocessing, the same target
//!   determination and the same F1–F9 edits as any other forwarded request — through the same code,
//!   which is the point. `V-03` was a private path that skipped all four.
//!
//! What makes this a function rather than a [`ResponseContext`](crate::context::ResponseContext) is
//! the absence of a server transaction to answer. A context exists to aggregate responses and
//! eventually produce one; an `ACK` has none, so every refusal a context could reach — §7's `480`,
//! §4's `483` — is unavailable here. Modelling it as a context whose `Respond` effects the driver
//! quietly discarded would put that protocol rule in the driver, where the harness cannot see it and
//! where the next driver would have to reinvent it.
//!
//! So the outcome is total and explicit: either a request and the hop it goes to, or a reason it
//! cannot go anywhere. **Never a silent drop** — the reason is the record that stands in for the
//! response SIP does not have.

use bytes::Bytes;
use sipx_sip::Request;

use crate::config::ProxyConfig;
use crate::forward::{ForwardError, ForwardPlan, forward};
use crate::route;
use crate::types::{TokenCarriage, TokenVerdict};
use crate::validate::{Refusal, validate};

/// What to do with an `ACK` for a 2xx (§7.2 K3).
#[derive(Debug)]
pub enum AckRoute {
    /// Forward this, with no transaction of its own and no response, ever.
    Forward {
        /// The copy as it goes on the wire: `Max-Forwards` decremented, our `Via` pushed, the
        /// `Route` set preprocessed, no `Record-Route` added (RFC 6141 — a mid-dialog
        /// `Record-Route` changes no established route set).
        request: Box<Request>,
        /// The URI whose address it must reach — F7, off the copy.
        next_hop: Bytes,
    },
    /// A popped platform `Route` carried a token: it is verified before this `ACK` goes anywhere
    /// (P2), and [`route_ack`] is called again with the verdict.
    ///
    /// The same rule as the response context's [`Effect::VerifyToken`](crate::Effect::VerifyToken)
    /// and for the same reason — an `ACK` for a 2xx is a separately routed request (K3) and takes
    /// §5 like any other. What differs is only the answer available when it fails: a context has a
    /// `403`, and this has a record.
    Verify {
        /// The governing token — the first-popped entry's.
        token: Bytes,
        /// The pair's other entry, for affinity-token §8 S9.
        partner: Option<Bytes>,
    },
    /// It cannot be forwarded, and there is no response to send instead. The reason, for the record.
    Unroutable(AckRefusal),
}

/// Why an `ACK` was not forwarded.
///
/// Every variant is a **drop with a reason**. An `ACK` has no response in SIP (RFC 3261 §17.1.1.3),
/// which [cluster-config](https://github.com/codewandler/sipx-clstr/blob/main/docs/specs/cluster-config.md)
/// §8 V11 already relies on for the admission bound, so there is no status to answer with and
/// inventing one would put a response on a transaction that has none. What is available is saying
/// so, which is what this type is for.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AckRefusal {
    /// §4 refused it. The refusal's status is what a *respondable* method would have been answered;
    /// here it is only the reason the `ACK` stopped.
    Refused(Refusal),
    /// F1–F9 could not build a forwardable copy — an unparseable target, or `Record-Route`
    /// configuration that does not parse.
    NotForwardable(ForwardError),
    /// P3 for a method that has no response: a platform `Route` carried a token that did not
    /// verify.
    ///
    /// A request gets `403 Forbidden` and this gets a record, but the *decision* is identical —
    /// there is no fallback routing and no degraded mode. Forwarding it anyway because an `ACK`
    /// cannot be refused out loud would make the one message that concludes a call the one message
    /// a forged token still buys.
    UnverifiableToken,
}

impl AckRefusal {
    /// Why, in one static phrase — for a log line, and structurally incapable of carrying anything
    /// the far end sent.
    #[must_use]
    pub fn describe(&self) -> &'static str {
        match self {
            Self::Refused(Refusal::Drop) => "the ACK is not well-formed enough to forward",
            Self::Refused(Refusal::UnsupportedScheme) => {
                "the Request-URI's scheme is not forwarded"
            }
            Self::Refused(Refusal::TooManyHops) => "Max-Forwards reached zero",
            Self::Refused(Refusal::LoopDetected) => "the ACK came back round a loop",
            Self::Refused(Refusal::MaxBreadthExceeded) => "Max-Breadth reached zero",
            Self::Refused(Refusal::BadExtension(_)) => {
                "Proxy-Require names an unsupported extension"
            }
            Self::NotForwardable(_) => "no forwardable copy could be built",
            Self::UnverifiableToken => "the Route's affinity token did not verify",
        }
    }
}

/// Route an `ACK` for a 2xx: §§4, 5, 5.1 and §7's edits, and the hop it goes to.
///
/// The target set is predetermined by §5.1 T1 whatever the `To` tag says, because §17.1.1.3 settles
/// it for this method: the `ACK` for a 2xx is addressed to the dialog's remote target, and a proxy
/// that resolved that Request-URI as an address of record would deliver the acknowledgement to
/// whatever the registrar happened to hold under it — or, finding nothing, drop the one message that
/// concludes the call.
///
/// `verdict` is the answer to a previous call's [`AckRoute::Verify`], and `None` on the first call.
/// A tokened `ACK` therefore cannot reach [`AckRoute::Forward`] without one having been supplied —
/// the ordering P2/P3 requires, made a property of the signature rather than of a driver's memory.
pub fn route_ack(
    request: Request,
    config: &ProxyConfig,
    verdict: Option<&TokenVerdict>,
) -> AckRoute {
    let validated = match validate(&request, config) {
        Ok(validated) => validated,
        Err(refusal) => return AckRoute::Unroutable(AckRefusal::Refused(refusal)),
    };

    let mut request = request;
    let carriage = route::preprocess(&mut request, config);

    // §5 P2/P3, before F1–F9 — the same order and the same rules as the response context's, through
    // the same preprocessing. A private shortcut past them is what `V-03` was.
    match (carriage, verdict) {
        (Some(_), Some(TokenVerdict::Invalid)) => {
            return AckRoute::Unroutable(AckRefusal::UnverifiableToken);
        }
        (Some(TokenCarriage { token, partner }), None) => {
            return AckRoute::Verify { token, partner };
        }
        (Some(_), Some(TokenVerdict::Valid { .. })) | (None, _) => {}
    }

    let target = route::predetermined_target(&request);

    let plan = ForwardPlan {
        original: &request,
        validated: &validated,
        target: &target,
        // One copy, never a fork: an `ACK` acknowledges one response from one branch.
        index: 0,
        parallel_branches: 1,
        // RFC 6141, and the same rule `is_dialog_forming` applies to a re-INVITE: a mid-dialog
        // `Record-Route` does not alter an established route set, so it is bytes for nothing.
        record_route: false,
        tokens: None,
    };
    match forward(&plan, config) {
        // F7's next hop comes back with the copy: it depends on whether F6 reformatted the copy
        // for a strict router, which only `forward` knows (`PX-16`).
        Ok((_, forwarded, next_hop)) => AckRoute::Forward {
            request: Box::new(forwarded),
            next_hop,
        },
        Err(error) => AckRoute::Unroutable(AckRefusal::NotForwardable(error)),
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::config::CookieKey;
    use sipx_sip::{HeaderName, Method, RequestBuilder, Uri};

    fn config() -> ProxyConfig {
        ProxyConfig::new(
            "edge-1.example",
            Bytes::from_static(b"<sip:edge-1.example:5060;lr>"),
            CookieKey::new(Bytes::from_static(b"key")),
        )
    }

    /// An `ACK` for a 2xx as a phone builds one (RFC 3261 §13.2.2.4): the Request-URI is the
    /// dialog's remote target and the `Route` set is what the `Record-Route` established.
    fn ack(remote_target: &str, routes: &[&str], max_forwards: &str) -> Request {
        let mut builder = RequestBuilder::new(
            Method::Ack,
            Uri::parse(Bytes::copy_from_slice(remote_target.as_bytes())).expect("a URI"),
        )
        .header(HeaderName::CallId, "ack-tests")
        .unwrap()
        .cseq(1, &Method::Ack)
        .unwrap()
        .header(HeaderName::From, "<sip:alice@a.example>;tag=af")
        .unwrap()
        .header(HeaderName::To, "<sip:bob@b.example>;tag=bt")
        .unwrap()
        .header(HeaderName::MaxForwards, max_forwards.to_owned())
        .unwrap()
        .header(
            HeaderName::Via,
            "SIP/2.0/UDP alice.example;branch=z9hG4bK-a",
        )
        .unwrap();
        for route in routes {
            builder = builder
                .header(HeaderName::Route, (*route).to_owned())
                .unwrap();
        }
        builder.build()
    }

    fn header(request: &Request, name: &HeaderName) -> Option<String> {
        request
            .headers
            .value(name)
            .map(|value| String::from_utf8_lossy(&value).trim().to_owned())
    }

    #[test]
    fn a_route_set_ack_goes_to_the_remote_target_with_our_route_popped() {
        let outcome = route_ack(
            ack(
                "sip:bob@10.0.0.1:5062",
                &["<sip:edge-1.example:5060;lr>"],
                "70",
            ),
            &config(),
            None,
        );
        let AckRoute::Forward { request, next_hop } = outcome else {
            panic!("an ACK with a reachable remote target is forwarded: {outcome:?}");
        };
        assert_eq!(
            String::from_utf8_lossy(&next_hop),
            "sip:bob@10.0.0.1:5062",
            "our own Route was popped, so the remote target is the next hop"
        );
        assert_eq!(header(&request, &HeaderName::Route), None);
        assert_eq!(
            header(&request, &HeaderName::MaxForwards).as_deref(),
            Some("69")
        );
        assert_eq!(header(&request, &HeaderName::RecordRoute), None);
        assert!(
            header(&request, &HeaderName::Via).is_some_and(|via| via.contains("edge-1.example")),
            "a forwarded request carries our Via (F8)"
        );
    }

    #[test]
    fn a_second_proxys_route_is_the_next_hop_and_the_target_is_untouched() {
        let outcome = route_ack(
            ack(
                "sip:bob@10.0.0.1:5062",
                &["<sip:edge-1.example:5060;lr>", "<sip:p2.example;lr>"],
                "70",
            ),
            &config(),
            None,
        );
        let AckRoute::Forward { request, next_hop } = outcome else {
            panic!("forwarded: {outcome:?}");
        };
        assert_eq!(String::from_utf8_lossy(&next_hop), "sip:p2.example;lr");
        assert_eq!(
            String::from_utf8_lossy(&request.uri.to_bytes()),
            "sip:bob@10.0.0.1:5062",
            "the Request-URI stays the dialog's remote target"
        );
    }

    #[test]
    fn an_unforwardable_ack_is_an_explicit_outcome_and_never_a_response() {
        let outcome = route_ack(ack("sip:bob@10.0.0.1:5062", &[], "0"), &config(), None);
        let AckRoute::Unroutable(refusal) = outcome else {
            panic!("Max-Forwards: 0 cannot be forwarded: {outcome:?}");
        };
        assert_eq!(refusal, AckRefusal::Refused(Refusal::TooManyHops));
        assert_eq!(refusal.describe(), "Max-Forwards reached zero");
    }

    #[test]
    fn a_tokened_ack_asks_for_a_verdict_before_it_is_forwarded() {
        // K3 takes §5 like any other request, so P2 applies: the token is verified *before* the one
        // message that concludes a call goes anywhere. Answering it out loud is what an `ACK` cannot
        // do — deciding is not.
        let tokened = ack(
            "sip:bob@10.0.0.1:5062",
            &["<sip:edge-1.example:5060;lr;aft=AQGgoaKj>"],
            "70",
        );
        let AckRoute::Verify { token, partner } = route_ack(tokened.clone(), &config(), None)
        else {
            panic!("a carried token is verified before the ACK is forwarded");
        };
        assert_eq!(token, Bytes::from_static(b"AQGgoaKj"));
        assert_eq!(partner, None, "one platform Route is not a pair");

        // P3 — the same hard reject a request gets, in the only currency this method has.
        let outcome = route_ack(tokened.clone(), &config(), Some(&TokenVerdict::Invalid));
        let AckRoute::Unroutable(refusal) = outcome else {
            panic!("a token that did not verify buys no routing: {outcome:?}");
        };
        assert_eq!(refusal, AckRefusal::UnverifiableToken);

        // And a verified one routes exactly as an untokened ACK does.
        let outcome = route_ack(
            tokened,
            &config(),
            Some(&TokenVerdict::Valid {
                tenant: "t1".to_owned(),
            }),
        );
        let AckRoute::Forward { next_hop, .. } = outcome else {
            panic!("a verified token routes the ACK: {outcome:?}");
        };
        assert_eq!(String::from_utf8_lossy(&next_hop), "sip:bob@10.0.0.1:5062");
    }

    #[test]
    fn two_aft_parameters_are_refused_a_layer_below_this_one() {
        // §5's "exactly one `aft` per platform URI" needs no check here, and this is why: RFC 3261
        // §19.1.1 forbids a repeated `uri-parameter` name outright, so the kernel refuses the URI
        // at parse time and the `Route` never becomes an `Address` we could recognize as ours. A
        // second check in this crate would be unreachable code claiming to hold a rule.
        let two = Bytes::from_static(b"<sip:edge-1.example:5060;lr;aft=AQGgoaKj;aft=AQGwsbKz>");
        assert!(
            sipx_sip::headers::Address::parse(&two, "Route").is_err(),
            "the kernel is what enforces §19.1.1; if that changes, §5 needs a check here"
        );
    }
}
